name: ci

on:
  push:
    branches: docker-ci

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Dockerfile
        uses: actions/checkout@v2
      -
        name: Checkout Joplin Server
        uses: actions/checkout@v2
        with:
          repository: laurent22/joplin
          ref: dev
          path: joplin
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./joplin/
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: |
            florider89/joplin-server:testing
